# Generated by Django 4.2.13 on 2024-08-02 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="interviewer",
        ),
        migrations.AddField(
            model_name="application",
            name="interviewer",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
