# Generated by Django 5.0.7 on 2024-07-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='template',
        ),
        migrations.AlterField(
            model_name='application',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.applicationtemplate'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.question'),
        ),
        migrations.DeleteModel(
            name='ApplicationTemplate',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
