# Generated by Django 4.2.14 on 2024-08-03 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='application',
            name='interviewer',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
