# Generated by Django 4.2.13 on 2024-08-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_remove_application_interviewer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Possible_date_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("possible_date", models.DateField()),
                (
                    "possible_ampm",
                    models.CharField(
                        choices=[("am", "오전"), ("pm", "오후")], max_length=50
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="interview_time",
            field=models.TimeField(
                blank=True,
                choices=[
                    ("09:00", "09:00"),
                    ("09:30", "09:30"),
                    ("10:00", "10:00"),
                    ("10:30", "10:30"),
                    ("11:00", "11:00"),
                    ("11:30", "11:30"),
                    ("12:00", "12:00"),
                    ("12:30", "12:30"),
                    ("13:00", "13:00"),
                    ("13:30", "13:30"),
                    ("14:00", "14:00"),
                    ("14:30", "14:30"),
                    ("15:00", "15:00"),
                    ("15:30", "15:30"),
                    ("16:00", "16:00"),
                    ("16:30", "16:30"),
                    ("17:00", "17:00"),
                    ("17:30", "17:30"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="interview_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="possible_date",
            field=models.ManyToManyField(
                blank=True, to="applicants.possible_date_list"
            ),
        ),
    ]
