# Generated by Django 4.2.13 on 2024-07-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_alter_application_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicants.applicationtemplate",
            ),
        ),
    ]
