# Generated by Django 4.2.13 on 2024-08-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0004_possible_date_list_max_possible_interview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="interview_date",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview_date",
                to="applicants.possible_date_list",
            ),
        ),
    ]
