# Generated by Django 5.0.7 on 2024-08-05 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0005_alter_application_interview_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interviewer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
