# Generated by Django 5.0.7 on 2024-08-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_comment'),
        ('applicants', '0006_alter_application_interviewer'),
    ]

    operations = [
    ]
