# Generated by Django 5.0.7 on 2024-08-05 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_remove_evaluationquestion_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='question_importance',
        ),
    ]
