# Generated by Django 5.0.7 on 2024-07-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.interviewquestion'),
        ),
        migrations.RemoveField(
            model_name='interviewquestiontemplate',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='InterviewQuestion',
        ),
        migrations.DeleteModel(
            name='InterviewQuestionTemplate',
        ),
    ]
